FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN apt-get update && apt-get install -y libpq-dev ffmpeg tesseract-ocr libopencv-dev pennylane
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ ./src/
COPY k8s/ ./k8s/
COPY docs/ ./docs/
CMD ["uvicorn", "src.services.backend_service:app", "--host", "0.0.0.0", "--port", "8000"]