#!/bin/bash
export PGHOST=$PGHOST
export PGPORT=$PGPORT
export PGDATABASE=$PGDATABASE
export PGUSER=$PGUSER
export PGPASSWORD=$PGPASSWORD
export NEO4J_URI=$NEO4J_URI
export NEO4J_USER=$NEO4J_USER
export NEO4J_PASSWORD=$NEO4J_PASSWORD
echo "Environment variables set."